# SPDX-License-Identifier: MIT
# Copyright (c) 2025 shun
name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    env:
      ROS2_WS: /root/ros2_ws
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        shell: bash
        run: |
          mkdir -p "${ROS2_WS}/src/mypkg"
          cp -a . "${ROS2_WS}/src/mypkg/"
          source /opt/ros/humble/setup.bash
          bash -xv "${ROS2_WS}/src/mypkg/test/test.bash"
